# Generated by Django 3.1.7 on 2021-05-30 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_allstockes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllStockes',
        ),
    ]
