# Generated by Django 3.2.4 on 2021-06-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_allstockes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allstockes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
