# Generated by Django 3.1.7 on 2021-05-24 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='featured',
        ),
    ]
